package classes.enums;

public enum Endpoint {
    GET_TASKS,
    GET_TASKS_ID,
    GET_EPICS,
    GET_EPICS_ID,
    GET_EPICS_ID_SUBTUSKS,
    GET_SUBTASKS,
    GET_SUBTASKS_ID,
    GET_HYSTORY,
    GET_PRIORITIZED,

    POST_TASKS,
    POST_EPICS,
    POST_SUBTASKS,

    DELETE_TASKS_ID,
    DELETE_EPICS_ID,
    DELETE_SUBTASKS_ID,

    ERROR_404,
    ERROR_406,

    UNKNOWN
}
